apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: RoyalHaskoningDHV/kes-python-client
  description: Kes Python Client
  links:
    - icon: dashboard
      title: GitHub
      url: https://github.com/RoyalHaskoningDHV/kes-python-client
  name: kes-python-client
  tags:
    - python
    - sdk
  title: Kes Python Client
spec:
  type: library
  lifecycle: production
  owner: team-bubblegum
  system: kes
