# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import table_pb2 as table__pb2


class TableStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.readTable = channel.unary_unary(
                '/kes.Table/readTable',
                request_serializer=table__pb2.ReadTableRequest.SerializeToString,
                response_deserializer=table__pb2.TableReply.FromString,
                )
        self.addRows = channel.unary_unary(
                '/kes.Table/addRows',
                request_serializer=table__pb2.AddRowsRequest.SerializeToString,
                response_deserializer=table__pb2.AddRowsReply.FromString,
                )
        self.deleteRows = channel.unary_unary(
                '/kes.Table/deleteRows',
                request_serializer=table__pb2.DeleteRowsRequest.SerializeToString,
                response_deserializer=table__pb2.DeleteRowsReply.FromString,
                )


class TableServicer(object):
    """Missing associated documentation comment in .proto file."""

    def readTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteRows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TableServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'readTable': grpc.unary_unary_rpc_method_handler(
                    servicer.readTable,
                    request_deserializer=table__pb2.ReadTableRequest.FromString,
                    response_serializer=table__pb2.TableReply.SerializeToString,
            ),
            'addRows': grpc.unary_unary_rpc_method_handler(
                    servicer.addRows,
                    request_deserializer=table__pb2.AddRowsRequest.FromString,
                    response_serializer=table__pb2.AddRowsReply.SerializeToString,
            ),
            'deleteRows': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteRows,
                    request_deserializer=table__pb2.DeleteRowsRequest.FromString,
                    response_serializer=table__pb2.DeleteRowsReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kes.Table', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Table(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def readTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kes.Table/readTable',
            table__pb2.ReadTableRequest.SerializeToString,
            table__pb2.TableReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def addRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kes.Table/addRows',
            table__pb2.AddRowsRequest.SerializeToString,
            table__pb2.AddRowsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteRows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kes.Table/deleteRows',
            table__pb2.DeleteRowsRequest.SerializeToString,
            table__pb2.DeleteRowsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
