"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import table_pb2

class TableStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    readTable: grpc.UnaryUnaryMultiCallable[
        table_pb2.ReadTableRequest,
        table_pb2.TableReply]

    addRows: grpc.UnaryUnaryMultiCallable[
        table_pb2.AddRowsRequest,
        table_pb2.AddRowsReply]

    deleteRows: grpc.UnaryUnaryMultiCallable[
        table_pb2.DeleteRowsRequest,
        table_pb2.DeleteRowsReply]


class TableServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def readTable(self,
        request: table_pb2.ReadTableRequest,
        context: grpc.ServicerContext,
    ) -> table_pb2.TableReply: ...

    @abc.abstractmethod
    def addRows(self,
        request: table_pb2.AddRowsRequest,
        context: grpc.ServicerContext,
    ) -> table_pb2.AddRowsReply: ...

    @abc.abstractmethod
    def deleteRows(self,
        request: table_pb2.DeleteRowsRequest,
        context: grpc.ServicerContext,
    ) -> table_pb2.DeleteRowsReply: ...


def add_TableServicer_to_server(servicer: TableServicer, server: grpc.Server) -> None: ...
